version: "3.9"

services:
  db:
    image: mysql:latest
    container_name: zidship_mysql8
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - 3866:3386

  web:
    build: .
    container_name: zidship_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
