# Generated by Django 4.0.1 on 2022-01-25 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shipments.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentstatus',
            old_name='at_courier_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='shipmentstatus',
            old_name='at_courier_status',
            new_name='external_code',
        ),
        migrations.AlterUniqueTogether(
            name='shipmentstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentstatus',
            name='code',
            field=models.CharField(choices=[('PROCCESSING', 'proccessing'), ('PENDING', 'pending'), ('CONFIRMED', 'confirmed'), ('IN_PROGRESS', 'in_progress'), ('DELIVERED', 'delivered'), ('PENDING_CANCELATION', 'pending-cancelation'), ('CANCELED', 'canceled')], db_index=True, default=shipments.enums.ShipmentStatusEnum['PROCCESSING'], max_length=100),
        ),
        migrations.AddField(
            model_name='shipmentstatus',
            name='external_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_method', to='shipments.shipmentmethod'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_status', to='shipments.shipmentstatus'),
        ),
        migrations.AlterUniqueTogether(
            name='shipmentstatus',
            unique_together={('code', 'courier', 'external_code')},
        ),
        migrations.RemoveField(
            model_name='shipmentstatus',
            name='status',
        ),
    ]
