# Generated by Django 4.0.1 on 2022-01-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_courierapisettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courierapisettings',
            name='access_token',
            field=models.TextField(null=True),
        ),
    ]
